Console output doesn't say the measurement started on 09/01/2020 but on 10/01/2020. This is not 
an error: this is because the PlanetLab Node apparently crashed or re-booted during the actual 
09/01/2020 measurement. Therefore, said measurement had to be re-started upon realizing the 
problem the next day in order to ensure a dataset for this VP was available. Since the second 
measurement didn't end up in a crash, it's likely the problem came from the PlanetLab node rather 
than from SAGE itself.
